export const FETCH_PHOTOS = 'FETCH_PHOTOS'
export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER' 
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT' 
export const REQUEST_PHOTOS = 'REQUEST_PHOTOS'
